### PR TITLE
New table

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by f3r** [comment]
@harrychenca mine :)

**Comment by ghost** [comment]
nooo

**Comment by ghost** [comment]
it's not finished

**Comment by ghost** [comment]
I'm working on it right now!!!!!!!!!!!;kuf1wkuyborcwuor f

**Comment by f3r** [comment]
Well... if you don't want the code to be reviewed... it's best to just push the branch, a PR means you want it merged or you have a question.... no?

**Comment by ghost** [comment]
it's been reviewed by Harry, but we agreed that I would push a new feature before merge

**Pull request closed without merging**
